### ISSUE TITLE
Help required with understanding path-degree product calculation

### ISSUE THREAD

**Issue by yuvaramsingh94** [hetio/hetnetpy#51]
Hi,
   This is Yuvaram a Master's student working on heterogeneous network. I am trying to understand the Path-degree product calculation from your [Paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004259#article1.body1.sec4.sec3.sec6.p1). I don't understand what is metaedge specific degrees along the path and why each edge contributes to 2. Can you provide an example or a simple calculation. This will help me in using your work for my project. 

Thanks
Yuvaram

**Comment by dhimmel** [comment]
[Figure 2D](https://doi.org/10.1371/journal.pcbi.1004259.g002) from the paper is the best visualization:

> ![image](https://github.com/hetio/hetnetpy/assets/1117703/d231a688-d39a-4c8f-987a-9ed2169f6d79)

Since each edge has a source and target node, two degrees exist for each edge. These degrees are metaedge specific (only counting edges of the same type).

Here are two implementations from this library if this helps understand. First the networkx/python implementation:

https://github.com/hetio/hetnetpy/blob/e1ff1f8296b766dd5a63e5870a8a1a7d82427a80/hetnetpy/pathtools.py#L32-L34

And second the neo4j/cypher implementation

https://github.com/hetio/hetnetpy/blob/e1ff1f8296b766dd5a63e5870a8a1a7d82427a80/test/pathtools_test.py#L82-L92

**Comment by yuvaramsingh94** [comment]
Thanks for quick reply any clearing the doubt.
